project:
  type: website
  output-dir: docs

website:
  favicon: bluebox.jpeg
  title: "Bernice Abanda"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - text: "Data Viz"
        menu: 
         - text: "Shakespeare"
           href: shakespearse.html
         - text: "Netflix Titles Analysis"
           href: netflix_titles.html
         - text: "Simulation"
           href: project3.html
         - text: "WAC_Visualization"
           href: project4.html
           
      

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    page-layout: full
    menu:
     color: orange


