project:
  type: website
  output-dir: docs

website:
  favicon: bluebox.jpeg
  title: "Bernice Abanda"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - text: "Data Viz"
        menu: 
         - text: "Shakespeare"
           href: shakespearse.html
         - text: Netflix Titles Analysis
         - text: "Simulaion"
           href: project3.html
      

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    page-layout: full


